[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
nom = "7.1.3"
strum = { version = "0.25", features = ["derive"] }
glam = "0.24.2"
itertools = "0.12.0"
petgraph = "0.6.4"
rayon = "1.8.0"
thiserror = "1.0.50"
divan = "0.1.3"
